//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_characters_H
#define METASPRITE_characters_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define characters_TILE_ORIGIN 0
#define characters_TILE_W 8
#define characters_TILE_H 8
#define characters_WIDTH 648
#define characters_HEIGHT 24
#define characters_TILE_COUNT 243
#define characters_PALETTE_COUNT 1
#define characters_COLORS_PER_PALETTE 4
#define characters_TOTAL_COLORS 4

BANKREF_EXTERN(characters)

extern const palette_color_t characters_palettes[4];
extern const uint8_t characters_tiles[3888];

#endif
